spring.application.name=cart-api

# The URL (Notice we removed the username and password from here!)
spring.datasource.url=jdbc:postgresql://ep-cold-feather-ajy4a01w.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require

# The Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rsN2Hy4Azeub

# Tells Hibernate to auto-create our tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect